services:
  - type: web
    name: django-backend
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: django-backend.onrender.com
      - key: DATABASE_URL
        sync: false
