services:
  - type: web
    name: django-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn mybackend.wsgi"
    envVars:
      - key: DJANGO_ALLOWED_HOSTS
        value: "django-backend.onrender.com"
      - key: DJANGO_SECRET_KEY
        generateValue: true
