# Generated by Django 5.1.6 on 2025-03-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacion_mm', models.CharField(max_length=50)),
                ('designacion_pulg', models.CharField(max_length=50)),
                ('d', models.FloatField()),
                ('h', models.FloatField()),
                ('tw', models.FloatField()),
                ('bf', models.FloatField()),
                ('tf', models.FloatField()),
                ('peso', models.FloatField()),
                ('area', models.FloatField()),
                ('ix', models.FloatField()),
                ('zx', models.FloatField()),
                ('sx', models.FloatField()),
                ('rx', models.FloatField()),
                ('iy', models.FloatField()),
                ('zy', models.FloatField()),
                ('sy', models.FloatField()),
                ('ry', models.FloatField()),
                ('j', models.FloatField()),
                ('cw', models.FloatField()),
            ],
        ),
    ]
