# Generated by Django 5.1.6 on 2025-03-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacion_mm', models.CharField(max_length=50)),
                ('designacion_pulg', models.CharField(max_length=50)),
                ('d', models.FloatField()),
                ('T', models.FloatField()),
                ('tw', models.FloatField()),
                ('bf', models.FloatField()),
                ('tf', models.FloatField()),
                ('k', models.FloatField()),
                ('k1', models.FloatField()),
                ('peso', models.FloatField()),
                ('area', models.FloatField()),
                ('b2ft', models.FloatField()),
                ('htw', models.FloatField()),
                ('ix', models.FloatField()),
                ('zx', models.FloatField()),
                ('sx', models.FloatField()),
                ('rx', models.FloatField()),
                ('iy', models.FloatField()),
                ('zy', models.FloatField()),
                ('sy', models.FloatField()),
                ('ry', models.FloatField()),
                ('j', models.FloatField()),
                ('cw', models.FloatField()),
            ],
        ),
    ]
