# Generated by Django 5.1.6 on 2025-03-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybackend', '0004_hr_ic_ie_irr_ld_li_oc_orc_orr_os_tr_zf'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField()),
                ('unidad', models.CharField(max_length=10)),
                ('costo_directo', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
