# Generated by Django 5.1.6 on 2025-03-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybackend', '0005_conceptoobra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptoobra',
            name='clave',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
