# Generated by Django 5.1.6 on 2025-03-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybackend', '0006_alter_conceptoobra_clave'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=40, unique=True)),
                ('descripcion', models.TextField()),
                ('unidad', models.CharField(max_length=10)),
                ('costo_directo', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Infraestructura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=40, unique=True)),
                ('descripcion', models.TextField()),
                ('unidad', models.CharField(max_length=10)),
                ('costo_directo', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='SCPT_AP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=40, unique=True)),
                ('descripcion', models.TextField()),
                ('unidad', models.CharField(max_length=10)),
                ('costo_directo', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='SCPT_BP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=40, unique=True)),
                ('descripcion', models.TextField()),
                ('unidad', models.CharField(max_length=10)),
                ('costo_directo', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='SEP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=40, unique=True)),
                ('descripcion', models.TextField()),
                ('unidad', models.CharField(max_length=10)),
                ('costo_directo', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
