# Generated by Django 5.1.6 on 2025-04-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybackend', '0007_ceas_infraestructura_scpt_ap_scpt_bp_sep'),
    ]

    operations = [
        migrations.AddField(
            model_name='orc',
            name='d',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='orc',
            name='t',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='orr',
            name='b',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='orr',
            name='d',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='orr',
            name='t',
            field=models.FloatField(default=0.0),
        ),
    ]
