# Generated by Django 5.1.6 on 2025-04-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybackend', '0008_orc_d_orc_t_orr_b_orr_d_orr_t'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ie',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irr',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hp',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
