# Generated by Django 5.1.6 on 2025-05-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybackend', '0009_hr_peso_ie_peso_irr_peso_alter_hp_peso'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAL_ARENA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(max_length=30)),
                ('Calhidra', models.FloatField()),
                ('Arena', models.FloatField()),
                ('Agua', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CEMENTO_ARENA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(max_length=30)),
                ('Cemento', models.FloatField()),
                ('Arena', models.FloatField()),
                ('Agua', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CEMENTO_ARENA_CERNIDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(max_length=30)),
                ('Cemento', models.FloatField()),
                ('Arena', models.FloatField()),
                ('Agua', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CEMENTO_CALHIDRA_ARENA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(max_length=30)),
                ('Cemento', models.FloatField()),
                ('Calhidra', models.FloatField()),
                ('Arena', models.FloatField()),
                ('Agua', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CONCRETO_OBRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Clasificacion', models.CharField(max_length=30)),
                ('fc', models.CharField(max_length=30)),
                ('Revenimiento', models.CharField(max_length=30)),
                ('Agregado', models.CharField(max_length=30)),
                ('Cemento', models.FloatField()),
                ('Grava', models.FloatField()),
                ('Arena', models.FloatField()),
                ('Agua', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MORTERO_ARENA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(max_length=30)),
                ('Mortero', models.FloatField()),
                ('Arena', models.FloatField()),
                ('Agua', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='hp',
            name='peso',
            field=models.FloatField(),
        ),
    ]
